### PR TITLE
release 3.2.2

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
main focus here is to get a new release that is cythonized with a current cython, so it will work on python 3.11 also.

also, pyfuse3 should be tested for all supported python versions and I got rid of travis-ci, using github actions now.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@nikratio would you please add me as maintainer on https://pypi.org/project/pyfuse3/ so I can release this as 3.2.2?

trio just released 0.21 which also works with py311.

would be good so borgbackup can continue to use pyfuse3, even on python 3.11 (I currently had to switch that to llfuse, which already works on py311 to make our CI work).

shall I point pypi metadata to this repo rather than your archived one?

**Comment by Nikratio** [comment]
I'd rather not have PyPi provide a different version of pyfuse3 than the one available from https://github.com/libfuse/pyfuse3/, or have different sets of maintainers for either.

How about this - I'll either do another one off release of pyfuse3 with the above changes, or I unarchive the GitHub project with you as a maintainer? (Since you've already been maintaining llfuse for a while, I'm happy to skip over the 6 month period mentioned in the README)

**Comment by ThomasWaldmann** [comment]
Guess unarchiving the original repo and adding me as maintainer would be good. I can't really develop this, but at least I hopefully can provide minimal maintenance to keep it working or fix obvious issues.

I didn't want to create a new pyfuse3 project on pypi, but update the original one, that's why I was asking for adding me there.

**Comment by ThomasWaldmann** [comment]
superseded by https://github.com/libfuse/pyfuse3/pull/56

**Comment by ThomasWaldmann** [comment]
@Nikratio thanks for unarchiving / adding me!

**Pull request closed without merging**
